version: '2'
services:
  nest:
    build: .
    container_name: mails

    volumes:
      - ./src:/app/src
      - .env:/app/.env
    ports:
      - 3001:3001
    networks:
      - expose_apis

networks:
  expose_apis:
    name: expose_apis
